[package]
name                 = "kallax-tracker-grpc-client"
description          = "Tracker gRPC client"
version.workspace    = true
authors.workspace    = true
homepage.workspace   = true
readme.workspace     = true
repository.workspace = true
license.workspace    = true
edition.workspace    = true
categories.workspace = true
keywords.workspace   = true

[dependencies]
async-trait = "0.1"

tonic = { version = "0.10", features = ["gzip"] }

http = "0.2"

snafu = "0.7"

kallax-primitives    = { path = "../../primitives" }
kallax-tracker-proto = { path = "../proto" }
