# syntax=docker/dockerfile:1.4

# This is the build stage for kallax. Here we create the binary in a temporary image.
FROM ghcr.io/thxnet/ci-containers/substrate-based:build-2023.05.20-41956af as builder

WORKDIR /build
COPY . /build

RUN cargo build --locked --release

# This is the 2nd stage: a very small image where we copy the kallax binary."
FROM docker.io/library/ubuntu:22.04 as kallax

LABEL description="Container image for Kallax" \
    io.thxnet.image.type="final" \
    io.thxnet.image.authors="contact@thxlab.io" \
    io.thxnet.image.vendor="thxlab.io" \
    io.thxnet.image.description="Utilities for setting up and managing Substrate-based blockchains" \
    org.opencontainers.image.source="https://github.com/thxnet/kallax"

COPY --from=builder /build/target/release/kallax /usr/local/bin

RUN <<EOF
#!/usr/bin/env bash

set -eu

useradd -m -u 1000 -U -s /bin/sh -d /kallax thxnet

# unclutter and minimize the attack surface
rm -rf /usr/bin /usr/sbin

# check if executable works in this container
/usr/local/bin/kallax --version

EOF

USER thxnet

ENTRYPOINT ["/usr/local/bin/kallax"]
