pub const THREAD_NAME: &str = "kallax";

pub const TRACKER_DEFAULT_PORT: u16 = 53973;
pub const TRACKER_DEFAULT_PEER_TIME_TO_LIVE_SECONDS: u64 = 60;

pub const KALLAX_SESSION_KEY_MNEMONIC_PHRASE_ENV: &str = "KALLAX_SESSION_KEY_MNEMONIC_PHRASE";
